"""add playlist and playlist_tracks tables.

Revision ID: e9512c2d3a7a
Revises: 4e1932e243f2
Create Date: 2026-09-23 19:39:26.099416

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "e9512c2d3a7a"
down_revision = "4e1932e243f2"
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Run the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "playlists",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("subsonic_id", sa.String(length=100), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("song_count", sa.Integer(), nullable=False),
        sa.Column("duration_seconds", sa.Integer(), nullable=False),
        sa.Column("created", sa.String(length=50), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_playlists_subsonic_id"), "playlists", ["subsonic_id"], unique=True
    )
    op.create_table(
        "playlist_tracks",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("playlist_id", sa.Integer(), nullable=False),
        sa.Column("track_id", sa.Integer(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["playlist_id"], ["playlists.id"], ondelete="cascade"),
        sa.ForeignKeyConstraint(["track_id"], ["tracks.id"], ondelete="cascade"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.alter_column("tracks", "artist_id", existing_type=sa.INTEGER(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Undo the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("tracks", "artist_id", existing_type=sa.INTEGER(), nullable=False)
    op.drop_table("playlist_tracks")
    op.drop_index(op.f("ix_playlists_subsonic_id"), table_name="playlists")
    op.drop_table("playlists")
    # ### end Alembic commands ###
