"""add subsonic fields.

Revision ID: c90eedbe8d73
Revises: 8caca4abd7b4
Create Date: 2026-09-11 22:34:44.247973

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "c90eedbe8d73"
down_revision = "8caca4abd7b4"
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Run the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "artists",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "albums",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("artist_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=True),
        sa.Column("release", sa.Integer(), nullable=True),
        sa.Column("cover_art_url", sa.String(length=500), nullable=True),
        sa.ForeignKeyConstraint(["artist_id"], ["artists.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "tracks",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("artist_id", sa.Integer(), nullable=False),
        sa.Column("album_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("duration_seconds", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["album_id"], ["albums.id"], ondelete="cascade"),
        sa.ForeignKeyConstraint(
            ["artist_id"],
            ["artists.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column(
        "user", sa.Column("subsonic_server_url", sa.String(length=500), nullable=False)
    )
    op.add_column(
        "user", sa.Column("subsonic_username", sa.String(length=255), nullable=False)
    )
    op.add_column(
        "user", sa.Column("subsonic_token", sa.String(length=255), nullable=False)
    )
    op.add_column(
        "user", sa.Column("subsonic_salt", sa.String(length=255), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Undo the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "subsonic_salt")
    op.drop_column("user", "subsonic_token")
    op.drop_column("user", "subsonic_username")
    op.drop_column("user", "subsonic_server_url")
    op.drop_table("tracks")
    op.drop_table("albums")
    op.drop_table("artists")
    # ### end Alembic commands ###
