"""add subsonic id and indexes.

Revision ID: 4e1932e243f2
Revises: c90eedbe8d73
Create Date: 2026-09-16 22:40:30.273116

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "4e1932e243f2"
down_revision = "c90eedbe8d73"
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Run the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "albums", sa.Column("subsonic_id", sa.String(length=100), nullable=False)
    )
    op.create_index(op.f("ix_albums_artist_id"), "albums", ["artist_id"], unique=False)
    op.create_index(
        op.f("ix_albums_subsonic_id"), "albums", ["subsonic_id"], unique=True
    )
    op.create_index(op.f("ix_albums_title"), "albums", ["title"], unique=False)
    op.add_column(
        "artists", sa.Column("subsonic_id", sa.String(length=100), nullable=False)
    )
    op.create_index(op.f("ix_artists_name"), "artists", ["name"], unique=False)
    op.create_index(
        op.f("ix_artists_subsonic_id"), "artists", ["subsonic_id"], unique=True
    )
    op.add_column(
        "tracks", sa.Column("subsonic_id", sa.String(length=100), nullable=False)
    )
    op.create_index(op.f("ix_tracks_album_id"), "tracks", ["album_id"], unique=False)
    op.create_index(op.f("ix_tracks_artist_id"), "tracks", ["artist_id"], unique=False)
    op.create_index(
        op.f("ix_tracks_subsonic_id"), "tracks", ["subsonic_id"], unique=True
    )
    op.create_index(op.f("ix_tracks_title"), "tracks", ["title"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Undo the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_tracks_title"), table_name="tracks")
    op.drop_index(op.f("ix_tracks_subsonic_id"), table_name="tracks")
    op.drop_index(op.f("ix_tracks_artist_id"), table_name="tracks")
    op.drop_index(op.f("ix_tracks_album_id"), table_name="tracks")
    op.drop_column("tracks", "subsonic_id")
    op.drop_index(op.f("ix_artists_subsonic_id"), table_name="artists")
    op.drop_index(op.f("ix_artists_name"), table_name="artists")
    op.drop_column("artists", "subsonic_id")
    op.drop_index(op.f("ix_albums_title"), table_name="albums")
    op.drop_index(op.f("ix_albums_subsonic_id"), table_name="albums")
    op.drop_index(op.f("ix_albums_artist_id"), table_name="albums")
    op.drop_column("albums", "subsonic_id")
    # ### end Alembic commands ###
